### ISSUE TITLE
About Update!

### ISSUE THREAD

**Issue by secfb** [Senanfurkan/Chaos-Recon#1]
Hi Furkan
projectdiscovery updated the download link as below.
https://chaosproject.projectdiscovery.io/uber.zip

In addition, projectdiscovery updated the subdomain list file. They made the lists intertwined.  Is there a way to overcome this problem?
```bash 
cat uber.com.txt_old 
```
`
1.dev.uber.com2.dev.uber.com3.dev.uber.com331759.uber.com4.dev.uber.com5.dev.uber.coma.dev.uber.coma5.dev.uber.comaa.dev.uber.comaalee.dev.uber.comaandrade.dev.uber.comaandrade0.dev.uber.comaandrade1.dev.uber.comaandrade10.dev.uber.comaandrade2.dev.uber.comaandrade3.dev.uber.comaaratee.dev.uber.comaarong.dev.uber.comaarong1.dev.uber.comab.dev.uber.comabahouth.dev.uber.comabe1.dev.uber.comabe2.dev.uber.comabe3.dev.uber.comabeinstein.dev.uber.comabg.dev.uber.comabq.dev.uber.comaccessibility.uber.comaccounts.dev.uber.comaccounts.uber.comachal.dev.uber.comachal0.dev.uber.comachiang.dev.uber.comacidburn.dev.uber.comacmilan.dev.uber.comactuarial.dev.uber.comacura-57-7.dev.uber.comacura-a8-7.dev.uber.comacura-acclaim-2.dev.uber.comacura-allante-3.dev.uber.comacura-altima-7.dev.uber.comacura-astra-4.dev.uber.comacura-carens-4.dev.uber.comacura-daytona-8.dev.uber.comacura-enclave-4.dev.uber.comacura-equinox-3.dev.uber.comacura-escape-5.dev.uber.comacura-excursion-4.dev.uber.comacura-fury-2.dev.uber.comacura-glk-9.dev.uber.comacura-impala-9.dev.uber.comacura-iq-3.dev.uber.comacura-iq-4.dev.uber.comacura-lancer-2.dev.uber.comacura-leganza-1.dev.uber.comacura-parkavenue-6.dev.uber.comacura-rendezvous-8.dev.uber.comacura-reno-4.dev.uber.comacura-runner-3.dev.uber.comacura-rx-7-9.dev.uber.comacura-sable-1.dev.uber.comacura-safari-1.dev.uber.comacura-sentra-7.dev.uber.comacura-sierra-9.dev.uber.comacura-solara-6.dev.uber.comacura-somerset-2.dev.uber.comacura-spectra-3.dev.uber.comacura-truck-3.dev.uber.comacura-volare-7.dev.uber.comacura-xg-7.dev.uber.comadamp.dev.uber.comadamz0.dev.uber.com
`

**Comment by Senanfurkan** [comment]
Hello, 

Thanks for the notification. I have updated the download link. 

You can use the following command to separate the subdomains manually for now. 

`sed 's/com/&\n/g' uber.com.txt`

I wrote about the issue to chaos team in discord. I am currently waiting for them to solve.

If they don't have action for it soon, once I have time I will update the script for it.

**Comment by secfb** [comment]
Thank you for the information. The projectdiscovery subdomain list has been restored.
Actually I didn't need it, but the command below didn't work.
`sed 's/com/&\n/g' uber.com.txt`

**Comment by Senanfurkan** [comment]
You may be using different version of sed maybe. Anyways, glad to hear it is solved! I close the issue then.
